# Generated by Django 3.2.7 on 2021-11-29 17:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('user_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('update_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('responsible', models.CharField(max_length=64)),
                ('status', model_utils.fields.StatusField(choices=[('to do', 'to do'), ('in progress', 'in progress'), ('done', 'done')], default='to do', max_length=100, no_check_for_status=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fri_site.user')),
            ],
        ),
    ]
