# Generated by Django 3.2.9 on 2021-11-24 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fri_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
