# Generated by Django 3.2.9 on 2021-11-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fri_site', '0002_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='update_id',
            field=models.IntegerField(null=True),
        ),
    ]
